name: doctor_consultation
description: A new Flutter application.
version: 1.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^7.1.8
  flutter_local_notifications: ^5.0.0-nullsafety.1
  photo_view: ^0.12.0
  intl: ^0.17.0
  webview_flutter: ^2.0.2
  flutter_webview_plugin: ^0.3.11
  permission_handler: ^8.0.0+1
  wakelock: ^0.5.0+2
  # Navigation
  auto_route: ^0.6.9
  introduction_screen: ^2.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  mask_text_input_formatter: ^1.2.1
  google_fonts: ^2.3.1
  # State management
  provider: ^5.0.0
  get_it: ^6.0.0
  flutter_spinkit: ^5.0.0
  connectivity: ^3.0.2
  email_validator: ^2.0.1
  url_launcher: ^6.0.2
  flutter_secure_storage: ^4.1.0
  cloud_firestore: ^1.0.1
  cloud_functions: ^3.2.11
  firebase_core: ^1.10.0
  firebase_storage: ^8.0.0
  flutter_datetime_picker: ^1.5.1
  # firebase_analytics: ^5.0.2
  firebase_messaging: ^11.2.12
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.0
  flutter_facebook_login: ^3.0.0
  cached_network_image: ^2.5.1
  image_picker: ^0.7.2+1
  bubble: ^1.2.1
  #video call
  agora_rtc_engine: ^4.0.1
  #search
  algolia: ^1.0.1
  flutter_sslcommerz: any
#  json_annotation: ^3.1.0
 # firebase_dynamic_links: ^5.0.3

  #SSLCommerz Payment
  #New Changes 
  country_picker: ^2.0.11
  get: ^4.6.1

  #Currency Picker
  currency_picker: ^2.0.9

  #LocalStorage
  shared_preferences: ^2.0.13
  flutter_neat_and_clean_calendar: ^0.3.4+17


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.6.10
  build_runner: null
  flutter_launcher_icons: ^0.9.0

# dependency_overrides:
#   sslcommerz_flutter: ^0.0.4
#   agora_rtc_engine: ^4.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/svg/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
