// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9XJqM2QRfRXvLVNXNkPvleBiciRZjQCI',
    appId: '1:660115681030:android:f61dfdd2dc1edcd4287887',
    messagingSenderId: '660115681030',
    projectId: 'medicbangladesh',
    databaseURL: 'https://medicbangladesh-default-rtdb.firebaseio.com',
    storageBucket: 'medicbangladesh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenDbN6VhjQxVTF6LAmEq5pZeBqviphjI',
    appId: '1:660115681030:ios:86aa758f027df48b287887',
    messagingSenderId: '660115681030',
    projectId: 'medicbangladesh',
    databaseURL: 'https://medicbangladesh-default-rtdb.firebaseio.com',
    storageBucket: 'medicbangladesh.appspot.com',
    androidClientId: '660115681030-gb5np0t7nduhg7jcm3qe78uftpmg06ri.apps.googleusercontent.com',
    iosClientId: '660115681030-7st7j6vtkl0pfqcrm3nfrp075vkt539j.apps.googleusercontent.com',
    iosBundleId: 'com.aniketmalik.doctorConsultation',
  );
}
